spring:
  config:
    activate:
      on-profile: dev

  # Mysql 설정
  datasource:
    url: jdbc:mysql://localhost:3306/mockuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: user1234!

  # PostgreSQL 설정
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/mockuser
  #    driver-class-name: org.postgresql.Driver
  #    username: postgres
  #    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #  database-platform: org.hibernate.dialect.PostgreSQLDialect
