spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/mockuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: user1234!

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
