spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    com.dtalk: DEBUG # ← 프로젝트 패키지에 맞게 수정
