spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

# 로그 설정 (선택적으로 활성화)
# logging:
#   level:
#     org.springframework.web: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#     org.springframework.orm.jpa: DEBUG
#     org.springframework.transaction: DEBUG
#     com.dtalk: DEBUG  # ← 실제 패키지에 맞게 변경
